Added a field and configuration value for custom PushOver notification sounds
snightshade/PushyFinder pull request #8
Opened 2024-07-09 18:40 UTC by Tarruck

Added a field and configuration value for custom PushOver notification sounds.

This probably could be done better, as PushOver has a way of getting a list with the customs sounds that the user has uploaded

2024-08-11 18:48 UTC, lostkagamine requested changes

2024-08-11 18:48 UTC, lostkagamine commented on PushyFinder/Retrieve/PushoverSoundsResponse.cs
> +    public class PushoverSoundsResponse
we don't need a whole file for this

2024-08-11 18:48 UTC, lostkagamine commented on PushyFinder/Retrieve/PushoverRetrieve.cs
> +        public static void GetSounds()
make this async and Task.run it

2024-08-11 18:48 UTC, lostkagamine commented on PushyFinder/Retrieve/PushoverRetrieve.cs
> +            var urlWithToken = $"{PUSHOVER_API}{Plugin.Configuration.PushoverAppKey}";
no; flurl has extension methods for doing this

2024-08-11 18:48 UTC, lostkagamine commented on PushyFinder/Retrieve/PushoverSoundsResponse.cs
> +    public class PushoverSoundsResponse
you definitely do not need a whole file, let alone a namespace, for this

2024-08-11 18:48 UTC, lostkagamine commented on PushyFinder/Windows/ConfigWindow.cs
> +            if (ImGui.Combo("Sound", ref soundIndex, Configuration.PushoverSoundList.ToArray(), Configuration.PushoverSoundList.Count))
.ToArray every draw frame causes a lot of undue allocations; cache it when the window opens

2024-08-11 18:48 UTC, lostkagamine commented on PushyFinder/Retrieve/PushoverRetrieve.cs
> +            var urlWithToken = $"{PUSHOVER_API}{Plugin.Configuration.PushoverAppKey}";
flurl has an API for this, this is just confusing

2024-08-11 18:48 UTC, lostkagamine commented on PushyFinder/Retrieve/PushoverRetrieve.cs
> +            Task.Run(async () =>
parent function should be async

2025-03-29 17:27 UTC, snightshade commented
Closing for inactivity

2025-03-29 17:27 UTC, closed without merging